services:
  frontend:
    build:
      context: .
    container_name: calendiary-front
    env_file:
      - .env
    ports:
      - "3000:80"
    networks:
      - calendiary_network

networks:
  calendiary_network:
    name: calendiary_network
    external: true  # 외부에서 이미 생성된 네트워크 사용